config:
    info: master branch, springcloud-config/config-dev.yml version=9
    
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       #當前數據源操作類型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驅動包
    jdbc-url: jdbc:mysql://localhost:3306/mycompany?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: jeff
    password: 660921

  jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect
     hibernate:
        ddl-auto: update
     show-sql: true
